### ISSUE TITLE
Unable to find a specification for `Uneri`

### ISSUE THREAD

**Issue by okahara** [jimmythai/Uneri#1]
Following your read me instructions and doing a `pod install` produces this error:

`[!] Unable to find a specification for 'Uneri'`

**Comment by jimmythai** [comment]
Could you run the command below?

`pod repo update`

**Comment by okahara** [comment]
@jimmythai that worked for me! Thank you and sorry for such a small issue.

**Comment by jimmythai** [comment]
@okahara No problem👍
